variable "ssh_key_file" {}
variable "cf_email" {}
variable "cf_token" {}
variable "cf_domain" {}
variable "publish_secret" {}
variable "azure_region" {}
variable "azure_tenant_id" {}
variable "azure_subscription_id" {}
variable "azure_client_id" {}
variable "azure_client_secret" {}
variable "azure_storage_prefix" {}
